/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */


/**
 * This file was generated by cantools version 37.0.1 Mon Dec 27 21:14:20 2021.
 */

#ifndef DBC_BMS_H
#define DBC_BMS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "DecentralizedLV-Boards/HVBoards/canstruct.h"

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define DBC_BMS_MSGID_0_X6_B0_FRAME_ID (0x6b0u)
#define DBC_BMS_MSGID_0_X6_B1_FRAME_ID (0x6b1u)
#define DBC_BMS_MSGID_0_X6_B2_FRAME_ID (0x6b2u)
#define DBC_BMS_MSGID_0_X6_B3_FRAME_ID (0x6b3u)
#define DBC_BMS_MSGID_0_X6_B4_FRAME_ID (0x6b4u)
#define DBC_BMS_MSGID_0_X6_B5_FRAME_ID (0x6b5u)
#define DBC_BMS_MSGID_0_X6_B6_FRAME_ID (0x6b6u)
#define DBC_BMS_MSGID_0_X36_CELLBCAST_FRAME_ID (0x36u)

/* Frame lengths in bytes. */
#define DBC_BMS_MSGID_0_X6_B0_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B1_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B2_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B3_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B4_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B5_LENGTH (8u)
#define DBC_BMS_MSGID_0_X6_B6_LENGTH (8u)
#define DBC_BMS_MSGID_0_X36_CELLBCAST_LENGTH (8u)

/* Extended or standard frame types. */
#define DBC_BMS_MSGID_0_X6_B0_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B1_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B2_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B3_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B4_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B5_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X6_B6_IS_EXTENDED (0)
#define DBC_BMS_MSGID_0_X36_CELLBCAST_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */



/**
 * Signals in message MSGID_0X6B0.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b0_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t pack_current;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t pack_inst_voltage;

    /**
     * Range: -
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t pack_soc;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint16_t relay_state;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 1720
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint16_t pack_current_encode();

    /**
    * Decode member
    */
    double pack_current_decode();

    /**
    * Is in range member
    */
    bool pack_current_is_in_range();


    /**
    * Encode member
    */
    uint16_t pack_inst_voltage_encode();

    /**
    * Decode member
    */
    double pack_inst_voltage_decode();

    /**
    * Is in range member
    */
    bool pack_inst_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_soc_encode();

    /**
    * Decode member
    */
    uint8_t pack_soc_decode();

    /**
    * Is in range member
    */
    bool pack_soc_is_in_range();


    /**
    * Encode member
    */
    uint16_t relay_state_encode();

    /**
    * Decode member
    */
    double relay_state_decode();

    /**
    * Is in range member
    */
    bool relay_state_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B1.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b1_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint16_t pack_dcl;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t pack_ccl;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t blank;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t high_temperature;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t low_temperature;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t failsafe_statuses;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 1721
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint16_t pack_dcl_encode();

    /**
    * Decode member
    */
    double pack_dcl_decode();

    /**
    * Is in range member
    */
    bool pack_dcl_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_ccl_encode();

    /**
    * Decode member
    */
    double pack_ccl_decode();

    /**
    * Is in range member
    */
    bool pack_ccl_is_in_range();


    /**
    * Encode member
    */
    uint8_t blank_encode();

    /**
    * Decode member
    */
    double blank_decode();

    /**
    * Is in range member
    */
    bool blank_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_temperature_encode();

    /**
    * Decode member
    */
    double high_temperature_decode();

    /**
    * Is in range member
    */
    bool high_temperature_is_in_range();


    /**
    * Encode member
    */
    uint8_t low_temperature_encode();

    /**
    * Decode member
    */
    double low_temperature_decode();

    /**
    * Is in range member
    */
    bool low_temperature_is_in_range();


    /**
    * Encode member
    */
    uint8_t failsafe_statuses_encode();

    /**
    * Decode member
    */
    double failsafe_statuses_decode();

    /**
    * Is in range member
    */
    bool failsafe_statuses_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B2.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b2_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t pack_ccl;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t pack_open_voltage;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t pack_amphours;

    /**
     * Range: -
     * Scale: 0.001
     * Offset: 0
     */
    uint8_t pack_resistance;

    /**
     * Range: -
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t pack_dod;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint8_t pack_summed_voltage;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t pack_abs_current_unsigned;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint8_t pack_ccl_encode();

    /**
    * Decode member
    */
    double pack_ccl_decode();

    /**
    * Is in range member
    */
    bool pack_ccl_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_open_voltage_encode();

    /**
    * Decode member
    */
    double pack_open_voltage_decode();

    /**
    * Is in range member
    */
    bool pack_open_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_amphours_encode();

    /**
    * Decode member
    */
    double pack_amphours_decode();

    /**
    * Is in range member
    */
    bool pack_amphours_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_resistance_encode();

    /**
    * Decode member
    */
    double pack_resistance_decode();

    /**
    * Is in range member
    */
    bool pack_resistance_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_dod_encode();

    /**
    * Decode member
    */
    double pack_dod_decode();

    /**
    * Is in range member
    */
    bool pack_dod_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_summed_voltage_encode();

    /**
    * Decode member
    */
    double pack_summed_voltage_decode();

    /**
    * Is in range member
    */
    bool pack_summed_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t pack_abs_current_unsigned_encode();

    /**
    * Decode member
    */
    double pack_abs_current_unsigned_decode();

    /**
    * Is in range member
    */
    bool pack_abs_current_unsigned_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B3.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b3_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t total_pack_cycles;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t average_temperature;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t internal_temperature;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t j1772_plug_state;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t j1772_ac_current_limit;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t high_cell_voltage;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t low_cell_voltage;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint8_t total_pack_cycles_encode();

    /**
    * Decode member
    */
    double total_pack_cycles_decode();

    /**
    * Is in range member
    */
    bool total_pack_cycles_is_in_range();


    /**
    * Encode member
    */
    uint8_t average_temperature_encode();

    /**
    * Decode member
    */
    double average_temperature_decode();

    /**
    * Is in range member
    */
    bool average_temperature_is_in_range();


    /**
    * Encode member
    */
    uint8_t internal_temperature_encode();

    /**
    * Decode member
    */
    double internal_temperature_decode();

    /**
    * Is in range member
    */
    bool internal_temperature_is_in_range();


    /**
    * Encode member
    */
    uint8_t j1772_plug_state_encode();

    /**
    * Decode member
    */
    double j1772_plug_state_decode();

    /**
    * Is in range member
    */
    bool j1772_plug_state_is_in_range();


    /**
    * Encode member
    */
    uint8_t j1772_ac_current_limit_encode();

    /**
    * Decode member
    */
    double j1772_ac_current_limit_decode();

    /**
    * Is in range member
    */
    bool j1772_ac_current_limit_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_cell_voltage_encode();

    /**
    * Decode member
    */
    double high_cell_voltage_decode();

    /**
    * Is in range member
    */
    bool high_cell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t low_cell_voltage_encode();

    /**
    * Decode member
    */
    double low_cell_voltage_decode();

    /**
    * Is in range member
    */
    bool low_cell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B4.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b4_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t low_opencell_voltage;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t high_opencell_voltage;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t avg_opencell_voltage;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint8_t low_cell_resistance;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint8_t high_cell_resistance;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint8_t avg_cell_resistance;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t low_cell_voltage_id;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint8_t low_opencell_voltage_encode();

    /**
    * Decode member
    */
    double low_opencell_voltage_decode();

    /**
    * Is in range member
    */
    bool low_opencell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_opencell_voltage_encode();

    /**
    * Decode member
    */
    double high_opencell_voltage_decode();

    /**
    * Is in range member
    */
    bool high_opencell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t avg_opencell_voltage_encode();

    /**
    * Decode member
    */
    double avg_opencell_voltage_decode();

    /**
    * Is in range member
    */
    bool avg_opencell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t low_cell_resistance_encode();

    /**
    * Decode member
    */
    double low_cell_resistance_decode();

    /**
    * Is in range member
    */
    bool low_cell_resistance_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_cell_resistance_encode();

    /**
    * Decode member
    */
    double high_cell_resistance_decode();

    /**
    * Is in range member
    */
    bool high_cell_resistance_is_in_range();


    /**
    * Encode member
    */
    uint8_t avg_cell_resistance_encode();

    /**
    * Decode member
    */
    double avg_cell_resistance_decode();

    /**
    * Is in range member
    */
    bool avg_cell_resistance_is_in_range();


    /**
    * Encode member
    */
    uint8_t low_cell_voltage_id_encode();

    /**
    * Decode member
    */
    double low_cell_voltage_id_decode();

    /**
    * Is in range member
    */
    bool low_cell_voltage_id_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B5.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b5_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t low_opencell_id;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t high_opencell_id;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t high_intres_id;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t low_intres_id;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t input_supply_voltage;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t j1772_ac_power_limit;

    /**
     * Range: -
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t j1772_ac_voltage;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint8_t low_opencell_id_encode();

    /**
    * Decode member
    */
    double low_opencell_id_decode();

    /**
    * Is in range member
    */
    bool low_opencell_id_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_opencell_id_encode();

    /**
    * Decode member
    */
    double high_opencell_id_decode();

    /**
    * Is in range member
    */
    bool high_opencell_id_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_intres_id_encode();

    /**
    * Decode member
    */
    double high_intres_id_decode();

    /**
    * Is in range member
    */
    bool high_intres_id_is_in_range();


    /**
    * Encode member
    */
    uint8_t low_intres_id_encode();

    /**
    * Decode member
    */
    double low_intres_id_decode();

    /**
    * Is in range member
    */
    bool low_intres_id_is_in_range();


    /**
    * Encode member
    */
    uint8_t input_supply_voltage_encode();

    /**
    * Decode member
    */
    double input_supply_voltage_decode();

    /**
    * Is in range member
    */
    bool input_supply_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t j1772_ac_power_limit_encode();

    /**
    * Decode member
    */
    double j1772_ac_power_limit_decode();

    /**
    * Is in range member
    */
    bool j1772_ac_power_limit_is_in_range();


    /**
    * Encode member
    */
    uint8_t j1772_ac_voltage_encode();

    /**
    * Decode member
    */
    double j1772_ac_voltage_decode();

    /**
    * Is in range member
    */
    bool j1772_ac_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X6B6.
 *
 * This ID Transmits at 8 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x6_b6_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t avg_cell_voltage;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint8_t high_cell_voltage;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t dtc_flags_1;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t dtc_flags_2;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t populated_cells;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t max_cell_number;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t hem_mode;

    /**
     * Range: -
     * Scale: 1.0
     * Offset: 0
     */
    uint8_t crc_checksum;

    /**
    * Encode member
    */
    uint8_t avg_cell_voltage_encode();

    /**
    * Decode member
    */
    double avg_cell_voltage_decode();

    /**
    * Is in range member
    */
    bool avg_cell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t high_cell_voltage_encode();

    /**
    * Decode member
    */
    double high_cell_voltage_decode();

    /**
    * Is in range member
    */
    bool high_cell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t dtc_flags_1_encode();

    /**
    * Decode member
    */
    double dtc_flags_1_decode();

    /**
    * Is in range member
    */
    bool dtc_flags_1_is_in_range();


    /**
    * Encode member
    */
    uint8_t dtc_flags_2_encode();

    /**
    * Decode member
    */
    double dtc_flags_2_decode();

    /**
    * Is in range member
    */
    bool dtc_flags_2_is_in_range();


    /**
    * Encode member
    */
    uint8_t populated_cells_encode();

    /**
    * Decode member
    */
    double populated_cells_decode();

    /**
    * Is in range member
    */
    bool populated_cells_is_in_range();


    /**
    * Encode member
    */
    uint8_t max_cell_number_encode();

    /**
    * Decode member
    */
    double max_cell_number_decode();

    /**
    * Is in range member
    */
    bool max_cell_number_is_in_range();


    /**
    * Encode member
    */
    uint8_t hem_mode_encode();

    /**
    * Decode member
    */
    double hem_mode_decode();

    /**
    * Is in range member
    */
    bool hem_mode_is_in_range();


    /**
    * Encode member
    */
    uint8_t crc_checksum_encode();

    /**
    * Decode member
    */
    double crc_checksum_decode();

    /**
    * Is in range member
    */
    bool crc_checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};
/**
 * Signals in message MSGID_0X36_CELLBCAST.
 *
 * This ID Transmits at 4 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct dbc_bms_msgid_0_x36_cellbcast_t:public CAN_STRUCT {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cell_id;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint16_t cell_voltage;

    /**
     * Range: -
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t cell_resistance;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t cell_balancing;

    /**
     * Range: -
     * Scale: 0.0001
     * Offset: 0
     */
    uint16_t cell_open_voltage;

    /**
     * Value = (0x36 + 8 + byte0 + byte1 + ... + byte6) & 0xFF
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t checksum;

    /**
    * Encode member
    */
    uint8_t cell_id_encode();

    /**
    * Decode member
    */
    double cell_id_decode();

    /**
    * Is in range member
    */
    bool cell_id_is_in_range();


    /**
    * Encode member
    */
    uint16_t cell_voltage_encode();

    /**
    * Decode member
    */
    double cell_voltage_decode();

    /**
    * Is in range member
    */
    bool cell_voltage_is_in_range();


    /**
    * Encode member
    */
    uint16_t cell_resistance_encode();

    /**
    * Decode member
    */
    double cell_resistance_decode();

    /**
    * Is in range member
    */
    bool cell_resistance_is_in_range();


    /**
    * Encode member
    */
    uint8_t cell_balancing_encode();

    /**
    * Decode member
    */
    double cell_balancing_decode();

    /**
    * Is in range member
    */
    bool cell_balancing_is_in_range();


    /**
    * Encode member
    */
    uint16_t cell_open_voltage_encode();

    /**
    * Decode member
    */
    double cell_open_voltage_decode();

    /**
    * Is in range member
    */
    bool cell_open_voltage_is_in_range();


    /**
    * Encode member
    */
    uint8_t checksum_encode();

    /**
    * Decode member
    */
    double checksum_decode();

    /**
    * Is in range member
    */
    bool checksum_is_in_range();


    /**
    * Pack member
    */
    int pack(uint8_t *dst_p, size_t size);
    
    /**
    * Unpack member
    */
    int unpack(const uint8_t *dst_p, size_t size);

};

#ifdef __cplusplus
}
#endif

#endif
